import { useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { MapPin, Clock, Phone, ShoppingBag, Plus, Minus, X, Search, Trash2, CheckCircle2, Utensils, Menu, Home, ClipboardList, User, ArrowRight, Flame, Pizza, CupSoda, Sandwich, IceCream, Beef } from "lucide-react";
import heroBurger from "@/assets/hero-burger.jpg";
import prodBurger from "@/assets/prod-burger.jpg";
import prodHotdog from "@/assets/prod-hotdog.jpg";
import prodFries from "@/assets/prod-fries.jpg";

type Produto = { id: string; nome: string; descricao: string; preco: number; categoria: string; imagem?: string; selo?: string };
type ItemSacola = Produto & { quantidade: number };

const produtos: Produto[] = [
  { id: "hamburguer", nome: "Hambúrguer", descricao: "Pão, carne, queijo, alface, tomate, repolho e pepino.", preco: 12, categoria: "Hambúrgueres", imagem: prodBurger },
  { id: "egg-hamburguer", nome: "Eggs-Hambúrguer", descricao: "Pão, carne, queijo, presunto, ovo e salada completa.", preco: 14, categoria: "Hambúrgueres", imagem: prodBurger },
  { id: "x-egg", nome: "X-Egg Hambúrgão", descricao: "Pão, 2 carnes, queijo, presunto, 2 ovos, batata e palha.", preco: 18, categoria: "Hambúrgueres", imagem: prodBurger },
  { id: "x-bacon", nome: "X-Bacon", descricao: "Pão, carne, queijo, ovo, bacon, presunto e salada.", preco: 18, categoria: "Hambúrgueres", imagem: prodBurger, selo: "Queridinho" },
  { id: "x-calabresa", nome: "X-Calabresa", descricao: "Pão, calabresa, bacon, ovo, queijo e salada.", preco: 18, categoria: "Hambúrgueres", imagem: prodBurger },
  { id: "x-dogao", nome: "X-Dogão", descricao: "Pão, salsicha, ovo, queijo, batata, bacon, calabresa e salada.", preco: 15, categoria: "Hambúrgueres", imagem: prodHotdog },
  { id: "x-lilhao", nome: "X-Lilhão", descricao: "Pão, 2 carnes, calabresa, salsicha, bacon, batata e salada.", preco: 22, categoria: "Hambúrgueres", imagem: prodBurger, selo: "Especial da casa" },
  { id: "calabacon", nome: "Calabacon", descricao: "Calabresa, bacon, ovo, queijo e salada.", preco: 16, categoria: "Hambúrgueres", imagem: prodBurger },
  { id: "carne-sol", nome: "Carne de Sol Completa", descricao: "Arroz, farofa especial, salada e macaxeira frita.", preco: 30, categoria: "Pratos", imagem: prodFries },
  { id: "misto", nome: "Misto Tradicional", descricao: "Pão de forma, queijo e presunto.", preco: 10, categoria: "Mistos" },
  { id: "misto-especial", nome: "Misto Especial", descricao: "Pão de forma, queijo, presunto e ovo.", preco: 12, categoria: "Mistos" },
  { id: "x-americano", nome: "X-Americano", descricao: "Pão de forma, queijo, presunto, ovo, alface, tomate e pepino.", preco: 14, categoria: "Mistos" },
  { id: "pizza-media", nome: "Pizza Média", descricao: "Queijo, presunto, molho e muito sabor.", preco: 45, categoria: "Pizzas" },
  { id: "refri-lata", nome: "Refrigerante Lata", descricao: "Consulte os sabores disponíveis.", preco: 7, categoria: "Bebidas" },
  { id: "refri-1l", nome: "Refrigerante 1L", descricao: "Geladinho para acompanhar.", preco: 12, categoria: "Bebidas" },
  { id: "refri-2l", nome: "Refrigerante 2L", descricao: "Ideal para compartilhar.", preco: 15, categoria: "Bebidas" },
  { id: "coca-1l", nome: "Coca-Cola 1L", descricao: "Geladinha para acompanhar.", preco: 13, categoria: "Bebidas" },
  { id: "coca-2l", nome: "Coca-Cola 2L", descricao: "Geladinha para compartilhar.", preco: 17, categoria: "Bebidas" },
  { id: "agua", nome: "Água Mineral", descricao: "Água mineral.", preco: 4, categoria: "Bebidas" },
  { id: "suco", nome: "Suco", descricao: "Consulte os sabores disponíveis.", preco: 7, categoria: "Bebidas" },
  { id: "copo", nome: "Sorvete no Copo", descricao: "Uma pausa geladinha e cremosa.", preco: 6, categoria: "Sorvetes" },
  { id: "taca", nome: "Taça", descricao: "Sobremesa gelada especial.", preco: 15, categoria: "Sorvetes" },
  { id: "cubinha", nome: "Cubinha", descricao: "Sobremesa gelada para dividir.", preco: 25, categoria: "Sorvetes" },
  { id: "combo-3", nome: "3 Hambúrgueres", descricao: "3 hambúrgueres por apenas R$ 33,00.", preco: 33, categoria: "Combos", selo: "Promoção" },
  { id: "combo-lilhao", nome: "Combo 2x Lilhão", descricao: "2 X-Lilhão por apenas R$ 38,00.", preco: 38, categoria: "Combos", selo: "Promoção" },
];
const categorias = ["Todos", "Hambúrgueres", "Combos", "Pratos", "Mistos", "Pizzas", "Bebidas", "Sorvetes"];
const dinheiro = (valor: number) => valor.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const categoriaIcone = (nome: string) => nome === "Hambúrgueres" ? Beef : nome === "Combos" ? Flame : nome === "Pizzas" ? Pizza : nome === "Bebidas" ? CupSoda : nome === "Sorvetes" ? IceCream : Sandwich;

function Header({ quantidade, abrirSacola }: { quantidade: number; abrirSacola: () => void }) {
  return <header className="sticky top-0 z-40 border-b border-white/10 bg-[#101010]/95 backdrop-blur-xl">
    <div className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-4 py-3 sm:px-6">
      <a href="#inicio" className="flex items-center gap-2.5 text-white"><span className="grid size-10 place-items-center rounded-full border-2 border-[#ffc400] bg-[#17150d] text-lg font-black text-[#ffc400]">L!</span><span><span className="block text-2xl font-black leading-none tracking-tight">Lilhão<span className="text-[#ffc400]">.</span></span><span className="mt-1 hidden text-[9px] font-bold uppercase tracking-[.16em] text-white/65 sm:block">Sabor que todo mundo aprova</span></span></a>
      <div className="flex items-center gap-2"><button type="button" onClick={abrirSacola} aria-label={`Abrir sacola. ${quantidade} ${quantidade === 1 ? "item" : "itens"}`} className="inline-flex min-h-10 items-center gap-2 rounded-full bg-[#ffc400] px-3.5 text-sm font-black text-black"><ShoppingBag className="size-5"/><span aria-live="polite" className="grid min-h-6 min-w-6 place-items-center rounded-full bg-black px-1 text-xs font-black tabular-nums text-[#ffc400]">{quantidade}</span></button><button aria-label="Menu" onClick={() => document.getElementById("cardapio")?.scrollIntoView({ behavior: "smooth" })} className="grid size-10 place-items-center rounded-full text-white"><Menu className="size-6"/></button></div>
    </div>
  </header>;
}

function Index() {
  const [categoria, setCategoria] = useState("Todos"); const [busca, setBusca] = useState(""); const [sacola, setSacola] = useState<ItemSacola[]>([]); const [sacolaAberta, setSacolaAberta] = useState(false); const [checkout, setCheckout] = useState(false); const [nomeCliente, setNomeCliente] = useState(""); const [bairro, setBairro] = useState(""); const [observacao, setObservacao] = useState(""); const [pedidoMontado, setPedidoMontado] = useState(false);
  const filtrados = useMemo(() => produtos.filter((p) => (categoria === "Todos" || p.categoria === categoria) && `${p.nome} ${p.descricao}`.toLowerCase().includes(busca.toLowerCase())), [categoria, busca]);
  const quantidade = sacola.reduce((t, i) => t + i.quantidade, 0); const subtotal = sacola.reduce((t, i) => t + i.preco * i.quantidade, 0);
  function adicionar(produto: Produto) { setSacola((atual) => { const existe = atual.find((i) => i.id === produto.id); return existe ? atual.map((i) => i.id === produto.id ? { ...i, quantidade: i.quantidade + 1 } : i) : [...atual, { ...produto, quantidade: 1 }]; }); setPedidoMontado(false); }
  function alterarQuantidade(id: string, delta: number) { setSacola((atual) => atual.map((i) => i.id === id ? { ...i, quantidade: i.quantidade + delta } : i).filter((i) => i.quantidade > 0)); setPedidoMontado(false); }
  function montarPedido(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!sacola.length || !nomeCliente.trim() || !bairro.trim()) return; setPedidoMontado(true); setCheckout(false); }
  const categoriasVisiveis = categoria === "Todos" ? categorias.slice(1) : [categoria];

  return <div className="min-h-screen bg-[#080909] pb-20 text-white md:pb-0">
    <Header quantidade={quantidade} abrirSacola={() => setSacolaAberta(true)} />
    <main>
      <section id="inicio" className="relative isolate flex min-h-[490px] items-center justify-center overflow-hidden border-b border-white/10 bg-black text-center sm:min-h-[570px]">
        <video className="absolute inset-0 -z-20 h-full w-full object-cover" autoPlay muted loop playsInline preload="metadata" poster={heroBurger} aria-hidden="true"><source src="https://videos.pexels.com/video-files/4253311/4253311-hd_1920_1080_25fps.mp4" type="video/mp4" /></video>
        <img src={heroBurger} alt="" className="absolute inset-0 -z-30 h-full w-full object-cover"/><div className="absolute inset-0 -z-10 bg-gradient-to-b from-black/55 via-black/55 to-[#080909]"/>
        <div className="relative mx-auto flex w-full max-w-5xl flex-col items-center px-5 py-16 sm:px-8 sm:py-20">
          <p className="mb-4 text-[11px] font-black uppercase tracking-[.2em] text-white/90 sm:text-sm">Hambúrgueres • Pizzas • Refeições • Sorvetes</p>
          <p className="text-xl font-black uppercase leading-none sm:text-3xl">Lanchonete do</p><h1 className="mt-1 text-7xl font-black uppercase leading-[.9] tracking-tight text-[#ffc400] drop-shadow-2xl sm:text-9xl">Lilhão<span className="text-white">.</span></h1>
          <p className="mt-4 text-sm font-bold uppercase tracking-wide text-white sm:text-lg">Sabor que vira tradição!</p>
          <a href="#cardapio" className="mt-7 inline-flex min-h-14 items-center justify-center gap-3 rounded-full bg-[#ffc400] px-10 text-base font-black text-black shadow-[0_8px_35px_rgba(255,196,0,.25)] transition hover:scale-[1.03]">Ver cardápio <span>↓</span></a>
          <p className="mt-5 max-w-xs text-sm italic text-white/80">Mais que um lanche, é tradição!</p>
        </div><div className="pointer-events-none absolute inset-x-0 bottom-0 h-16 bg-gradient-to-t from-[#080909] to-transparent"/>
      </section>

      <section id="cardapio" className="mx-auto max-w-7xl scroll-mt-20 px-3 py-5 sm:px-6 sm:py-10">
        <div className="mb-4 flex items-center gap-3 rounded-full border border-white/15 bg-[#171819] px-4 py-1"><Search className="size-5 shrink-0 text-white/45"/><input value={busca} onChange={(e) => setBusca(e.target.value)} placeholder="Buscar no cardápio..." className="min-h-11 w-full bg-transparent text-sm outline-none placeholder:text-white/40"/></div>
        <div className="-mx-1 mb-6 flex gap-2 overflow-x-auto px-1 pb-1">{categorias.map((item) => <button key={item} onClick={() => setCategoria(item)} className={`shrink-0 rounded-full border px-4 py-2.5 text-xs font-bold transition sm:text-sm ${categoria === item ? "border-[#ffc400] bg-[#ffc400] text-black" : "border-white/15 bg-[#111314] text-white/75 hover:border-[#ffc400]/50"}`}>{item}</button>)}</div>
        {categoriasVisiveis.map((cat) => { const itens = filtrados.filter((p) => p.categoria === cat); if (!itens.length) return null; const Icon = categoriaIcone(cat); return <section key={cat} className="mb-7 scroll-mt-24">
          <div className="mb-3 flex items-center justify-between"><h2 className="flex items-center gap-3 text-xl font-black sm:text-2xl"><Icon className="size-7 text-[#ffc400]"/><span>{cat}</span></h2><button onClick={() => setCategoria(cat)} className="flex items-center gap-1 text-xs font-medium text-white/65">Ver todos <ArrowRight className="size-4"/></button></div>
          <div className="space-y-2.5">{itens.map((p) => { const noCarrinho = sacola.find((i) => i.id === p.id)?.quantidade ?? 0; return <article key={p.id} className="flex min-h-[116px] overflow-hidden rounded-xl border border-white/15 bg-[#141617] transition hover:border-[#ffc400]/40">
            <div className="relative w-[112px] shrink-0 self-stretch overflow-hidden bg-black sm:w-36">{p.imagem ? <img src={p.imagem} alt={p.nome} loading="lazy" className="h-full min-h-[116px] w-full object-cover"/> : <div className="grid h-full min-h-[116px] place-items-center bg-gradient-to-br from-[#2a2412] to-[#111] text-4xl">{cat === "Bebidas" ? "🥤" : cat === "Sorvetes" ? "🍨" : cat === "Pizzas" ? "🍕" : cat === "Mistos" ? "🥪" : "🍔"}</div>}{p.selo && <span className="absolute left-1 top-1 rounded bg-[#ffc400] px-1.5 py-0.5 text-[8px] font-black uppercase text-black">{p.selo}</span>}</div>
            <div className="flex min-w-0 flex-1 items-center justify-between gap-2 p-3 sm:p-4"><div className="min-w-0 flex-1"><h3 className="text-[15px] font-bold leading-tight sm:text-lg">{p.nome}</h3><p className="mt-1 line-clamp-2 text-xs leading-relaxed text-white/60 sm:text-sm">{p.descricao}</p><p className="mt-1.5 text-lg font-black text-[#ffc400] sm:text-xl">{dinheiro(p.preco)}</p></div><button onClick={() => adicionar(p)} aria-label={`Adicionar ${p.nome}`} className="grid size-10 shrink-0 place-items-center rounded-full bg-[#ffc400] text-black transition hover:scale-105 hover:bg-yellow-300"><Plus className="size-5"/>{noCarrinho > 0 && <span className="sr-only">{noCarrinho} na sacola</span>}</button></div>
          </article>; })}</div>
        </section>; })}
        {filtrados.length === 0 && <p className="rounded-xl border border-white/10 p-8 text-center text-white/60">Nenhum item encontrado. Tente outra busca ou categoria.</p>}
        {categoria === "Todos" && !busca && <section className="mb-7"><div className="mb-3 flex items-center gap-3"><Flame className="size-7 text-[#ffc400]"/><h2 className="text-xl font-black sm:text-2xl">Combos em destaque</h2></div><div className="grid grid-cols-2 gap-3">{produtos.filter(p => p.categoria === "Combos").map(p => <article key={p.id} className="overflow-hidden rounded-xl border border-white/15 bg-[#141617]"><div className="flex h-24 items-center justify-center bg-gradient-to-br from-[#38100d] to-black text-5xl">🍔</div><div className="p-3"><p className="text-xs font-black uppercase text-white">{p.nome}</p><p className="mt-1 text-xl font-black text-[#ffc400]">{dinheiro(p.preco)}</p><button onClick={() => adicionar(p)} className="mt-2 flex min-h-9 w-full items-center justify-center gap-1 rounded-lg bg-[#ffc400] text-xs font-black text-black"><Plus className="size-4"/> Adicionar</button></div></article>)}</div></section>}
      </section>
      <section id="contato" className="border-t border-white/10 bg-[#111314]"><div className="mx-auto max-w-7xl px-4 py-10 sm:px-6"><div className="text-center"><p className="text-xs font-black uppercase tracking-[.2em] text-[#ffc400]">Estamos por aqui</p><h2 className="mt-2 text-2xl font-black sm:text-3xl">Lilhão, sabor que conquista</h2></div><div className="mx-auto mt-6 grid max-w-4xl gap-3 sm:grid-cols-3"><div className="rounded-xl border border-white/10 bg-white/[.03] p-4 text-center"><Clock className="mx-auto size-5 text-[#ffc400]"/><h3 className="mt-2 font-bold">Horários</h3><p className="mt-1 text-xs text-white/55">Consulte a disponibilidade do dia</p></div><div className="rounded-xl border border-white/10 bg-white/[.03] p-4 text-center"><Phone className="mx-auto size-5 text-[#ffc400]"/><h3 className="mt-2 font-bold">Pedidos</h3><p className="mt-1 text-xs text-white/55">(96) 9911-2135</p></div><div className="rounded-xl border border-white/10 bg-white/[.03] p-4 text-center"><MapPin className="mx-auto size-5 text-[#ffc400]"/><h3 className="mt-2 font-bold">Entrega</h3><p className="mt-1 text-xs text-white/55">Consulte a taxa para seu bairro</p></div></div></div></section>
    </main>
    <footer className="border-t border-white/10 px-4 py-6 text-center"><p className="font-black">Lilhão<span className="text-[#ffc400]">.</span></p><p className="mt-1 text-xs text-white/40">Feito com muito sabor © {new Date().getFullYear()} Lanchonete do Lilhão</p></footer>

    {/* Sacola flutuante: aparece somente com itens e fica oculta enquanto o drawer está aberto. */}
    {quantidade > 0 && !sacolaAberta && <button type="button" onClick={() => setSacolaAberta(true)} aria-label={`Abrir sacola com ${quantidade} ${quantidade === 1 ? "item" : "itens"}`} className="fixed bottom-24 right-4 z-40 grid size-14 place-items-center rounded-full bg-[#ffc400] text-black shadow-lg shadow-black/40 transition hover:scale-105 md:bottom-6 md:right-6"><ShoppingBag className="size-6"/><span aria-live="polite" className="absolute -right-1 -top-1 grid min-h-6 min-w-6 place-items-center rounded-full border-2 border-[#080909] bg-black px-1 text-[11px] font-black tabular-nums text-[#ffc400]">{quantidade}</span></button>}

    <nav className="fixed inset-x-0 bottom-0 z-30 grid grid-cols-4 border-t border-white/15 bg-[#101112]/95 px-2 py-2 backdrop-blur-xl md:hidden"><a href="#inicio" className="flex flex-col items-center gap-1 py-1 text-[10px] font-semibold text-[#ffc400]"><Home className="size-5"/>Início</a><a href="#cardapio" className="flex flex-col items-center gap-1 py-1 text-[10px] font-semibold text-white/60"><Utensils className="size-5"/>Cardápio</a><button onClick={() => setSacolaAberta(true)} className="flex flex-col items-center gap-1 py-1 text-[10px] font-semibold text-white/60"><span className="relative"><ClipboardList className="size-5"/>{quantidade > 0 && <span aria-live="polite" className="absolute -right-3 -top-2 grid min-h-4 min-w-4 place-items-center rounded-full bg-[#ffc400] px-1 text-[9px] font-black leading-none text-black">{quantidade}</span>}</span><span>Pedidos</span></button><a href="/conta" className="flex flex-col items-center gap-1 py-1 text-[10px] font-semibold text-white/60"><User className="size-5"/>Conta</a></nav>

    {sacolaAberta && <div className="fixed inset-0 z-50 flex justify-end bg-black/75" onClick={() => setSacolaAberta(false)}><aside role="dialog" aria-modal="true" aria-label="Minha sacola" onClick={(e) => e.stopPropagation()} className="flex h-full w-full max-w-lg flex-col border-l border-white/10 bg-[#111314] shadow-2xl">
      <div className="flex items-center justify-between border-b border-white/10 p-5"><div><p className="text-xs font-black uppercase tracking-widest text-[#ffc400]">Seu pedido</p><h2 className="mt-1 text-2xl font-black">Minha sacola <span className="text-white/40">({quantidade})</span></h2></div><button onClick={() => setSacolaAberta(false)} aria-label="Fechar sacola" className="grid size-10 place-items-center rounded-full border border-white/15"><X className="size-5"/></button></div>
      <div className="flex-1 overflow-y-auto p-4 sm:p-5">{pedidoMontado ? <div className="rounded-2xl border border-emerald-500/30 bg-emerald-500/10 p-5"><CheckCircle2 className="size-9 text-emerald-400"/><h3 className="mt-3 text-xl font-black">Pedido montado!</h3><p className="mt-2 text-sm text-white/70">Resumo pronto, {nomeCliente}. Esta versão ainda não envia o pedido à lanchonete.</p><div className="mt-4 rounded-xl bg-black/20 p-3 text-sm"><p><b>Nome:</b> {nomeCliente}</p><p><b>Bairro:</b> {bairro}</p>{observacao && <p><b>Observação:</b> {observacao}</p>}<p className="mt-2 font-black text-[#ffc400]">Subtotal: {dinheiro(subtotal)}</p></div><button onClick={() => { setPedidoMontado(false); setSacolaAberta(false); }} className="mt-4 min-h-11 w-full rounded-full bg-[#ffc400] font-extrabold text-black">Continuar navegando</button></div> : sacola.length === 0 ? <div className="py-16 text-center"><ShoppingBag className="mx-auto size-12 text-white/20"/><h3 className="mt-4 text-lg font-extrabold">Sua sacola está vazia</h3><p className="mt-2 text-sm text-white/50">Adicione algo delicioso do cardápio.</p><button onClick={() => setSacolaAberta(false)} className="mt-5 rounded-full bg-[#ffc400] px-5 py-3 text-sm font-extrabold text-black">Explorar cardápio</button></div> : <div className="space-y-3"><h3 className="mb-2 flex items-center gap-2 text-lg font-black"><ShoppingBag className="size-5 text-[#ffc400]"/> Itens do pedido</h3>{sacola.map((item) => <div key={item.id} className="flex gap-3 rounded-xl border border-white/10 bg-[#181a1b] p-3"><div className="size-[68px] shrink-0 overflow-hidden rounded-lg bg-black">{item.imagem ? <img src={item.imagem} alt={item.nome} className="h-full w-full object-cover"/> : <div className="grid h-full place-items-center text-2xl">🥤</div>}</div><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><div><h4 className="text-sm font-bold">{item.nome}</h4><p className="text-xs text-[#ffc400]">{dinheiro(item.preco)}</p></div><button onClick={() => setSacola((a) => a.filter((i) => i.id !== item.id))} aria-label={`Remover ${item.nome}`} className="text-white/35"><Trash2 className="size-4"/></button></div><div className="mt-2 flex items-center justify-between"><div className="flex items-center gap-2 rounded-full bg-white/[.06] p-1"><button onClick={() => alterarQuantidade(item.id, -1)} aria-label="Diminuir" className="grid size-7 place-items-center rounded-full bg-white/10"><Minus className="size-3.5"/></button><span className="min-w-4 text-center text-sm font-bold">{item.quantidade}</span><button onClick={() => alterarQuantidade(item.id, 1)} aria-label="Aumentar" className="grid size-7 place-items-center rounded-full bg-white/10"><Plus className="size-3.5"/></button></div><b className="text-sm text-[#ffc400]">{dinheiro(item.preco * item.quantidade)}</b></div></div></div>)}</div>}</div>
      {!pedidoMontado && sacola.length > 0 && <div className="border-t border-white/10 bg-[#141617] p-4 sm:p-5"><label className="mb-3 flex items-center gap-3 rounded-lg border border-white/10 bg-[#202223] px-3"><span className="text-white/40">▤</span><input value={observacao} onChange={(e) => setObservacao(e.target.value)} className="min-h-11 w-full bg-transparent text-sm outline-none placeholder:text-white/40" placeholder="Observações (opcional)"/></label><div className="mb-4 flex items-center justify-between"><span className="font-bold text-white/70">Subtotal</span><span className="text-2xl font-black text-white">{dinheiro(subtotal)}</span></div>{checkout ? <form onSubmit={montarPedido} className="space-y-3"><label className="block text-xs font-bold text-white/60">Seu nome<input required value={nomeCliente} onChange={(e) => setNomeCliente(e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-white/15 bg-black/20 px-3 text-base text-white outline-none focus:border-[#ffc400]" placeholder="Como podemos te chamar?"/></label><label className="block text-xs font-bold text-white/60">Bairro / local de entrega<input required value={bairro} onChange={(e) => setBairro(e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-white/15 bg-black/20 px-3 text-base text-white outline-none focus:border-[#ffc400]" placeholder="Informe seu bairro"/></label><button type="submit" className="min-h-12 w-full rounded-full bg-[#ffc400] font-black text-black">Finalizar pedido <ArrowRight className="ml-1 inline size-4"/></button><button type="button" onClick={() => setCheckout(false)} className="min-h-10 w-full text-sm font-bold text-white/50">Voltar à sacola</button></form> : <button onClick={() => setCheckout(true)} className="min-h-12 w-full rounded-full bg-[#ffc400] font-black text-black">Continuar pedido <ArrowRight className="ml-1 inline size-4"/></button>}<p className="mt-3 text-center text-[10px] leading-relaxed text-white/35">Taxa de entrega calculada à parte. O pedido ainda não é enviado à lanchonete nesta versão.</p></div>}
    </aside></div>}
  </div>;
}

export const Route = createFileRoute("/")({ component: Index });