// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcqiggjfozzbqcrzisqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjcWlnZ2pmb3p6YnFjcnppc3FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAwNDM3MjksImV4cCI6MjEwNTYxOTcyOX0.A0Ec8kUnmLI0wiRd71fhOWO642Lc5q6-6J9nbTN-Pc8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});